# Generated by Django 5.1.5 on 2025-04-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_add_rbac_and_privacy_features'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
